import type { Survey, SurveyQuestion } from '@/lib/survey-schema';

// ─────────────────────────────────────────────────────────────────────────
// Standard recruiting blocks — the *cached template*.
//
// Every screening survey we publish carries three fixed regions that never
// change between surveys:
//   1. 개인정보 수집 동의 (privacy-consent gate)      — first section
//   2. 연락 가능한 전화번호 (contact-phone notice)     — last section
//   3. 인적사항 (이름/출생년도/성별/기기 + 성의도 질문) — last section
//
// These used to be generated by the LLM on every request, which (a) burned
// output tokens and time, and (b) let the model drift on wording — a legal
// risk for the consent copy especially. We now treat them as a compiled-in
// template: the LLM is told NOT to produce them (see the survey-generation
// system prompt), and post-process injects them deterministically. This file
// is the single source of truth for that template — survey-postprocess.ts and
// the publish route both build on these constants.
// ─────────────────────────────────────────────────────────────────────────

export const PERSONAL_SECTION_TITLE = '인적사항';

// ── 개인정보 수집 동의 (consent) ──────────────────────────────────────────
export const PRIVACY_CONSENT_SECTION_TITLE = '개인정보 수집 동의';
export const PRIVACY_CONSENT_TITLE = '개인정보 수집 및 이용 동의';
export const PRIVACY_CONSENT_AGREE = '동의합니다';
export const PRIVACY_CONSENT_DENY = '동의하지 않습니다';
export const PRIVACY_CONSENT_DESCRIPTION = [
  '[수집 항목]',
  '- 응답자가 입력한 모든 응답 내용',
  '- 이름, 출생년도, 성별',
  '- 연락처 (전화번호)',
  '- 사용 기기 정보 (핸드폰 브랜드 / 모델명)',
  '',
  '[수집 목적]',
  '- 인터뷰 대상자 선정 심사',
  '- 선정된 응답자에게 인터뷰 일정 안내 및 연락',
  '- 인터뷰 결과 데이터의 익명화 분석',
  '',
  '[보유 기간]',
  '- 선정 대상자: 인터뷰 종료 후 30일 보관 후 자동 폐기',
  '- 미선정 대상자: 심사 완료 후 7일 보관 후 자동 폐기',
  '',
  '[동의 거부 권리]',
  '- 동의를 거부하실 권리가 있으며, 거부 시 인터뷰 참여가 불가합니다.',
  '- 동의 후에도 언제든지 요청을 통해 데이터 삭제가 가능합니다.',
].join('\n');

// ── 연락 가능한 전화번호 (contact phone) ──────────────────────────────────
export const MANDATORY_PHONE_NOTICE =
  '인터뷰 대상자로 선정되셨을 때 연락을 드릴 수 있도록 전화번호를 정확히 적어주세요';

// Fills in the parts of a SurveyQuestion the schema requires but a standard
// block doesn't use (scale fields, empty options) so callers only spell out
// what matters.
function makeStandardQuestion(
  partial: Partial<SurveyQuestion> & Pick<SurveyQuestion, 'kind' | 'title'>,
): SurveyQuestion {
  return {
    kind: partial.kind,
    title: partial.title,
    description: partial.description ?? '',
    required: partial.required ?? true,
    options: partial.options ?? [],
    scaleMin: partial.scaleMin ?? 0,
    scaleMax: partial.scaleMax ?? 0,
    scaleMinLabel: partial.scaleMinLabel ?? '',
    scaleMaxLabel: partial.scaleMaxLabel ?? '',
  };
}

export function buildPrivacyConsentQuestion(): SurveyQuestion {
  return makeStandardQuestion({
    kind: 'single_choice',
    title: PRIVACY_CONSENT_TITLE,
    description: PRIVACY_CONSENT_DESCRIPTION,
    options: [PRIVACY_CONSENT_AGREE, PRIVACY_CONSENT_DENY],
  });
}

export function buildPhoneQuestion(): SurveyQuestion {
  return makeStandardQuestion({
    kind: 'short_answer',
    title: '연락 가능한 전화번호',
    description: MANDATORY_PHONE_NOTICE,
  });
}

// The 인적사항 block, in fixed order. The trailing 100만원 long-answer is a
// response-sincerity probe and is part of the standard template — do not
// rewrite or trim it.
export function buildPersonalQuestions(): SurveyQuestion[] {
  return [
    makeStandardQuestion({ kind: 'short_answer', title: '이름' }),
    makeStandardQuestion({
      kind: 'short_answer',
      title: '출생년도 (4자리)',
      description: '예: 1990',
    }),
    makeStandardQuestion({
      kind: 'single_choice',
      title: '성별',
      options: ['여성', '남성', '응답하지 않음'],
    }),
    makeStandardQuestion({
      kind: 'single_choice',
      title: '사용 중인 핸드폰 브랜드',
      options: ['삼성', '애플', '기타'],
    }),
    makeStandardQuestion({
      kind: 'short_answer',
      title: '핸드폰 기기 모델명',
      description: '예: 아이폰 16, 갤럭시 S21',
    }),
    makeStandardQuestion({
      kind: 'long_answer',
      title:
        '만약 본인에게 자유롭게 사용할 수 있는 돈 100만원이 생긴다면, 어떻게 그 돈을 사용하고 싶으신가요? 저축은 할 수 없고 반드시 소비를 하셔야 합니다.',
    }),
  ];
}

// True when a section is one of the standard template regions — used by the
// editor to lock these sections (read-only) so the consent copy and 인적사항
// stay byte-identical across every published survey.
export function isStandardSectionTitle(title: string): boolean {
  const t = title ?? '';
  return (
    t.includes(PRIVACY_CONSENT_SECTION_TITLE) ||
    t.includes(PERSONAL_SECTION_TITLE)
  );
}

export type { Survey, SurveyQuestion };
